server:
  port: 8080
---
logging:
  file:
    name: devPlatformGateway.log
  level:
    reactor:
      netty: DEBUG
    org:
      springframework:
        cloud:
          gateway: DEBUG
---
management:
  endpoints:
    web:
      exposure:
        include: "health,loggers,metrics,mappings,conditions,info"
---
spring:
  cloud:
    kubernetes:
      enabled: false
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            preLogger: true
            postLogger: true
      routes:
        - id: user-svc
          uri: http://localhost:8081
          predicates:
            - Path=lb://webui/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback
            - name: UserFilter
              args:
                baseMessage: Spring Cloud Gateway UserFilter
                preLogger: true
                postLogger: true
          metadata:
            connect-timeout: 2500
            response-timeout: 2500